import { Restaurant } from './types';

export const demoRestaurant: Restaurant = {
  id: 'demo-001',
  name: "Bella Napoli",
  slug: "bella-napoli",
  cuisine: ["Italian", "Pizza", "Pasta"],
  description: "Authentic Neapolitan cuisine in the heart of the city. Family-owned since 1987, we use imported Italian ingredients and traditional recipes passed down three generations. Our wood-fired oven reaches 900°F for the perfect Neapolitan crust.",
  address: "142 Vine Street",
  city: "San Francisco",
  state: "CA",
  zip: "94103",
  country: "US",
  phone: "+1 (415) 555-0192",
  website: "https://bellanapoli.example.com",
  email: "info@bellanapoli.example.com",
  priceRange: "$$",
  rating: 4.8,
  reviewCount: 847,
  latitude: 37.7749,
  longitude: -122.4194,
  hours: {
    monday: { open: "11:30", close: "21:30", closed: false },
    tuesday: { open: "11:30", close: "21:30", closed: false },
    wednesday: { open: "11:30", close: "21:30", closed: false },
    thursday: { open: "11:30", close: "22:00", closed: false },
    friday: { open: "11:30", close: "23:00", closed: false },
    saturday: { open: "12:00", close: "23:00", closed: false },
    sunday: { open: "12:00", close: "21:00", closed: false },
  },
  specialties: [
    "Wood-fired Margherita Pizza",
    "Homemade Tagliatelle Bolognese",
    "Tiramisu (house-made daily)",
    "Imported Buffalo Mozzarella",
    "24-hour slow-cooked Osso Buco"
  ],
  amenities: [
    "Outdoor seating",
    "Private dining room",
    "Full bar",
    "Vegetarian options",
    "Vegan options",
    "Gluten-free pasta available",
    "Reservations accepted",
    "Wheelchair accessible",
    "Free WiFi"
  ],
  menu: [
    { name: "Margherita Pizza", description: "San Marzano tomatoes, buffalo mozzarella, fresh basil, extra virgin olive oil", price: 18, category: "Pizza", isVegetarian: true },
    { name: "Diavola Pizza", description: "Spicy salami, fior di latte, chili oil, oregano", price: 22, category: "Pizza" },
    { name: "Tagliatelle Bolognese", description: "Slow-cooked beef and pork ragù, Parmigiano-Reggiano", price: 24, category: "Pasta", isSignature: true },
    { name: "Cacio e Pepe", description: "Tonnarelli pasta, Pecorino Romano, black pepper", price: 20, category: "Pasta", isVegetarian: true },
    { name: "Osso Buco", description: "Braised veal shank, gremolata, saffron risotto", price: 38, category: "Secondi", isSignature: true },
    { name: "Caprese Salad", description: "Imported buffalo mozzarella, heirloom tomatoes, basil, aged balsamic", price: 16, category: "Antipasti", isVegetarian: true },
    { name: "Tiramisu", description: "House-made daily, mascarpone, espresso-soaked ladyfingers, cocoa", price: 12, category: "Dessert", isVegetarian: true, isSignature: true },
    { name: "Panna Cotta", description: "Vanilla bean, seasonal berry coulis", price: 10, category: "Dessert", isVegetarian: true, isGlutenFree: true },
  ],
  images: [],
  createdAt: new Date().toISOString(),
  plan: 'pro',
};
