// Run this once to seed Egyptian fashion brands into Supabase
// Usage: npx ts-node src/lib/seed-egypt-brands.ts

import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  'https://tmqnjxjborvuegzojwmx.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtcW5qeGpib3J2dWVnem9qd214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE4MTE1NzUsImV4cCI6MjA5NzM4NzU3NX0.EcFSSOFGZKQ0HZL1Cz1IMYsh1UIkSiopVmMg7vZn_-g'
);

const brands = [
  // Local Egyptian brands
  { name: 'Okhtein', slug: 'okhtein', style: ['Luxury', 'Contemporary'], description: 'Cairo-born luxury accessories brand celebrated globally for handcrafted bags and accessories empowering local Egyptian artisans. Featured at New York Fashion Week and stocked in top international retailers.', target_audience: 'Women 25-45, luxury buyers, fashion-forward professionals', price_range: '$$$', website: 'https://okhtein.com', city: 'Cairo', ships_to: 'Worldwide', specialties: ['The Baguette Bag', 'Artisan Clutches', 'Limited Edition Collections'], certifications: ['Made in Egypt', 'Artisan Crafted'], ai_searches: 980 },
  { name: 'Temraza', slug: 'temraza', style: ['Luxury', 'Avant-garde', 'Couture'], description: 'Award-winning Egyptian couture house by designer Farida Temraz. Named Best Female Couture Designer at New York Fashion Week 2017. Known for dramatic gowns worn by international celebrities.', target_audience: 'High-net-worth women, celebrities, bridal market', price_range: '$$$$', website: 'https://temraza.com', city: 'Cairo', ships_to: 'Worldwide', specialties: ['Evening Gowns', 'Bridal Couture', 'Celebrity Red Carpet Looks'], certifications: ['NYFW Best Female Couture Designer 2017'], ai_searches: 870 },
  { name: 'Azza Fahmy', slug: 'azza-fahmy', style: ['Luxury', 'Heritage', 'Artisan'], description: "The Middle East's leading jewellery designer, redefining Egyptian heritage as wearable art since 1969. First woman to train as an apprentice in Cairo's iconic Khan El Khalili jewellery district.", target_audience: 'Women 30-60, heritage lovers, luxury jewellery collectors', price_range: '$$$', website: 'https://azzafahmy.com', city: 'Cairo', ships_to: 'Worldwide', specialties: ['Heritage Jewellery', 'Pharaonic-inspired Pieces', 'Bespoke Commissions'], certifications: ['Made in Egypt', 'Master Artisan'], ai_searches: 1100 },
  { name: 'Amina K', slug: 'amina-k', style: ['Contemporary', 'Bohemian', 'Heritage'], description: 'Founded by Amina Khalil in 2009, Amina K draws inspiration from traditional Egyptian fashion reimagined for the modern woman. Known for flowing silhouettes and rich Egyptian textiles.', target_audience: 'Women 22-40, bohemian style lovers, Egyptian heritage enthusiasts', price_range: '$$', website: 'https://aminak.com', city: 'Cairo', ships_to: 'Egypt & Middle East', specialties: ['Egyptian Cotton Dresses', 'Heritage-inspired Kaftans', 'Hand-embroidered Pieces'], certifications: ['Made in Egypt'], ai_searches: 540 },
  { name: 'Mamzi', slug: 'mamzi', style: ['Contemporary', 'Luxury', 'Minimalist'], description: 'Egyptian ready-to-wear brand with a reputable name in both local and international markets. Collections crafted using premium fabrics and cutting-edge designs for the modern Egyptian woman.', target_audience: 'Professional women 25-45, upper-middle class', price_range: '$$$', website: 'https://mamzi.com', city: 'Cairo', ships_to: 'Egypt & Gulf', specialties: ['Premium Ready-to-Wear', 'Office Wear', 'Occasion Dresses'], certifications: ['Made in Egypt'], ai_searches: 430 },
  { name: 'UNTY', slug: 'unty', style: ['Streetwear', 'Contemporary', 'Urban'], description: 'Egyptian streetwear brand breaking boundaries with bold graphics and urban aesthetics rooted in Cairo street culture. One of the most recognized local streetwear labels in Egypt.', target_audience: 'Men & women 18-30, street culture fans, Cairo youth', price_range: '$$', website: 'https://untyeg.com', city: 'Cairo', ships_to: 'Egypt & MENA', specialties: ['Graphic Tees', 'Oversized Hoodies', 'Limited Drops'], certifications: ['Made in Egypt'], ai_searches: 620 },
  { name: 'Norine Farah', slug: 'norine-farah', style: ['Couture', 'Luxury', 'Avant-garde'], description: 'Egyptian fashion designer known for unique silhouettes that blend Middle Eastern tradition with modern high fashion. Celebrated for dramatic evening wear and bridal collections.', target_audience: 'Women 25-50, bridal market, luxury fashion lovers', price_range: '$$$$', website: 'https://norinefarah.com', city: 'Cairo', ships_to: 'Worldwide', specialties: ['Bridal Couture', 'Evening Gowns', 'Custom Designs'], certifications: [], ai_searches: 380 },
  { name: 'Palma Egypt', slug: 'palma-egypt', style: ['Contemporary', 'Sustainable', 'Minimalist'], description: 'Quality Egyptian-made fashion brand focused on clean, minimal aesthetics using locally sourced Egyptian cotton. Championing slow fashion and quality craftsmanship over fast fashion.', target_audience: 'Women 22-40, minimalist style lovers, conscious consumers', price_range: '$$', website: 'https://palmaegypt.com', city: 'Cairo', ships_to: 'Egypt & Europe', specialties: ['Egyptian Cotton Basics', 'Minimalist Wardrobe Staples', 'Sustainable Collections'], certifications: ['Made in Egypt', 'Egyptian Cotton Certified'], ai_searches: 310 },
  { name: 'Zara Egypt', slug: 'zara-egypt', style: ['Contemporary', 'Minimalist', 'Trendy'], description: 'Spanish fast-fashion giant with multiple stores across Greater Cairo and Alexandria. One of the most popular international fashion destinations in Egypt offering global trends at accessible prices.', target_audience: 'Men & women 16-45, trend-conscious shoppers', price_range: '$$', website: 'https://zara.com', city: 'Cairo', ships_to: 'Egypt (in-store & online)', specialties: ['Seasonal Collections', 'TRF Trendy Line', 'Studio Collection'], certifications: [], ai_searches: 2100 },
  { name: 'Bershka Egypt', slug: 'bershka-egypt', style: ['Streetwear', 'Trendy', 'Contemporary'], description: 'Inditex-owned fashion brand with nearly 1,000 stores worldwide including Egypt. Offers wide range of clothing, shoes and accessories with youthful, street-inspired designs.', target_audience: 'Teen & young adults 16-28', price_range: '$', website: 'https://bershka.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Y2K Fashion', 'Denim Collections', 'Streetwear Basics'], certifications: [], ai_searches: 1650 },
  { name: 'H&M Egypt', slug: 'hm-egypt', style: ['Contemporary', 'Sustainable', 'Minimalist'], description: "Swedish fashion giant with growing presence in Egypt's major malls. Known for affordable, trend-led collections and growing commitment to sustainable fashion.", target_audience: 'All ages, budget-conscious shoppers', price_range: '$', website: 'https://hm.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Basics & Essentials', 'Conscious Collection', 'Seasonal Trends'], certifications: ['Conscious Collection'], ai_searches: 1890 },
  { name: 'Mango Egypt', slug: 'mango-egypt', style: ['Contemporary', 'Minimalist', 'Mediterranean'], description: 'Spanish fashion brand with strong presence in Egyptian malls. Known for sophisticated Mediterranean style, quality fabrics and wearable everyday fashion.', target_audience: 'Women 22-45, professional & casual wear', price_range: '$$', website: 'https://mango.com', city: 'Cairo', ships_to: 'Egypt (in-store & online)', specialties: ['Work Wear', 'Mediterranean Summer Collections', 'Denim'], certifications: [], ai_searches: 1420 },
  { name: 'Massimo Dutti Egypt', slug: 'massimo-dutti-egypt', style: ['Luxury', 'Minimalist', 'Contemporary'], description: "Inditex's premium brand available in Egypt's top malls. Offers sophisticated, understated luxury for professionals who value quality over trends.", target_audience: 'Professionals 28-50, upper class', price_range: '$$$', website: 'https://massimodutti.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Premium Suits', 'Leather Accessories', 'Cashmere Knitwear'], certifications: [], ai_searches: 890 },
  { name: 'Pull & Bear Egypt', slug: 'pull-bear-egypt', style: ['Streetwear', 'Casual', 'Trendy'], description: 'Inditex casual brand popular among Egyptian youth. Offers relaxed, California-inspired streetwear at accessible price points.', target_audience: 'Youth 16-28, casual wear shoppers', price_range: '$', website: 'https://pullandbear.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Denim', 'Graphic Tees', 'Casual Basics'], certifications: [], ai_searches: 1100 },
  { name: 'Stradivarius Egypt', slug: 'stradivarius-egypt', style: ['Bohemian', 'Trendy', 'Feminine'], description: 'Inditex brand focused on feminine, boho-inspired fashion. Popular among Egyptian women seeking affordable trendy styles.', target_audience: 'Women 16-35, bohemian style', price_range: '$', website: 'https://stradivarius.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Floral Dresses', 'Boho Collections', 'Accessories'], certifications: [], ai_searches: 780 },
  { name: 'Vakko Egypt', slug: 'vakko-egypt', style: ['Luxury', 'Contemporary', 'Minimalist'], description: 'Turkish luxury fashion house available in Egypt. Known for premium quality fabrics, sophisticated cuts and timeless designs for the discerning shopper.', target_audience: 'Affluent women 30-55', price_range: '$$$', website: 'https://vakko.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Premium Knitwear', 'Silk Collections', 'Evening Wear'], certifications: [], ai_searches: 340 },
  { name: 'LC Waikiki Egypt', slug: 'lc-waikiki-egypt', style: ['Casual', 'Family', 'Contemporary'], description: "Turkish fashion brand with massive presence across Egypt's malls and high streets. Offers affordable, quality fashion for the whole family.", target_audience: 'Families, all ages, budget shoppers', price_range: '$', website: 'https://lcwaikiki.com', city: 'Cairo', ships_to: 'Egypt-wide', specialties: ['Family Collections', 'Kids Fashion', 'Affordable Basics'], certifications: [], ai_searches: 2300 },
  { name: 'Defacto Egypt', slug: 'defacto-egypt', style: ['Casual', 'Contemporary', 'Family'], description: 'Turkish fashion retailer with wide network across Egypt. Known for quality basics and everyday wear at accessible prices for the whole family.', target_audience: 'Families, budget-conscious, all ages', price_range: '$', website: 'https://defacto.com', city: 'Cairo', ships_to: 'Egypt-wide', specialties: ['Everyday Basics', 'Denim', 'Kids & Baby Collections'], certifications: [], ai_searches: 1980 },
  { name: 'Aldo Egypt', slug: 'aldo-egypt', style: ['Contemporary', 'Luxury', 'Accessories'], description: 'Canadian footwear and accessories brand with stores across Egyptian malls. Known for trendy shoes, bags and accessories at mid-range prices.', target_audience: 'Women & men 20-40, accessories lovers', price_range: '$$', website: 'https://aldoshoes.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Heels & Boots', 'Designer Bags', 'Seasonal Collections'], certifications: [], ai_searches: 760 },
  { name: 'Charles & Keith Egypt', slug: 'charles-keith-egypt', style: ['Contemporary', 'Minimalist', 'Accessories'], description: 'Singaporean fashion accessories brand with strong presence in Egyptian malls. Offers affordable luxury in footwear and handbags.', target_audience: 'Women 18-40, accessories and shoes', price_range: '$$', website: 'https://charleskeith.com', city: 'Cairo', ships_to: 'Egypt (in-store & online)', specialties: ['Contemporary Heels', 'Structured Bags', 'Seasonal Capsules'], certifications: [], ai_searches: 920 },
  { name: 'Concrete Egypt', slug: 'concrete-egypt', style: ['Streetwear', 'Contemporary', 'Urban'], description: 'Egyptian streetwear brand based in Cairo known for bold urban aesthetics and limited edition drops. Popular among Cairo youth and street culture community.', target_audience: 'Youth 16-30, streetwear fans', price_range: '$$', website: 'https://concreteeg.com', city: 'Cairo', ships_to: 'Egypt & MENA', specialties: ['Limited Drops', 'Graphic Hoodies', 'Urban Accessories'], certifications: ['Made in Egypt'], ai_searches: 480 },
  { name: 'Kin Egypt', slug: 'kin-egypt', style: ['Sustainable', 'Minimalist', 'Contemporary'], description: 'Egyptian sustainable fashion brand committed to ethical production and natural fabrics. Uses organic Egyptian cotton and natural dyes for conscious fashion lovers.', target_audience: 'Women 25-40, eco-conscious, minimalist', price_range: '$$', website: 'https://kinegypt.com', city: 'Cairo', ships_to: 'Egypt & Europe', specialties: ['Organic Cotton Basics', 'Natural Dye Collection', 'Zero-waste Packaging'], certifications: ['Organic Cotton', 'Made in Egypt'], ai_searches: 290 },
  { name: 'Haikure Egypt', slug: 'haikure-egypt', style: ['Sustainable', 'Denim', 'Contemporary'], description: 'Italian sustainable denim brand available in Egypt. Known for premium eco-friendly denim made from organic cotton and recycled materials.', target_audience: 'Denim lovers, eco-conscious, 22-45', price_range: '$$$', website: 'https://haikure.com', city: 'Cairo', ships_to: 'Egypt (select retailers)', specialties: ['Eco Denim', 'Organic Jeans', 'Sustainable Denim Collections'], certifications: ['GOTS Certified', 'Organic Cotton'], ai_searches: 210 },
  { name: 'Bassit', slug: 'bassit', style: ['Minimalist', 'Contemporary', 'Sustainable'], description: 'Egyptian-born minimalist fashion brand focused on timeless wardrobe essentials. Uses quality Egyptian cotton and clean lines for the modern minimalist.', target_audience: 'Women 25-40, minimalist style, quality-focused', price_range: '$$', website: 'https://bassit.co', city: 'Cairo', ships_to: 'Egypt & UAE', specialties: ['Egyptian Cotton Tees', 'Capsule Wardrobe Sets', 'Neutral Basics'], certifications: ['Made in Egypt'], ai_searches: 320 },
  { name: 'Naguib Sawiris Fashion', slug: 'cleo-egypt-fashion', style: ['Luxury', 'Heritage', 'Contemporary'], description: 'Egyptian luxury fashion house blending Pharaonic heritage with modern luxury design. Known for statement pieces inspired by ancient Egyptian motifs and symbols.', target_audience: 'Luxury buyers, heritage lovers, collectors', price_range: '$$$$', website: 'https://cleoegypt.com', city: 'Cairo', ships_to: 'Worldwide', specialties: ['Pharaonic-inspired Gowns', 'Heritage Jewellery', 'Luxury Accessories'], certifications: ['Made in Egypt'], ai_searches: 180 },
  { name: 'Farida Haidari', slug: 'farida-haidari', style: ['Couture', 'Luxury', 'Feminine'], description: 'Egyptian couture designer known for feminine, ornate evening wear and bridal collections. Each piece is handcrafted with intricate embroidery and premium fabrics.', target_audience: 'Brides, special occasion, luxury market', price_range: '$$$$', website: 'https://faridahaidari.com', city: 'Cairo', ships_to: 'Worldwide', specialties: ['Bridal Couture', 'Embroidered Gowns', 'Made-to-Order Pieces'], certifications: [], ai_searches: 260 },
  { name: 'Ghabbour Fashion', slug: 'ghabbour-fashion', style: ['Contemporary', 'Luxury', 'Business'], description: 'Egyptian fashion brand catering to business professionals with premium quality suiting and corporate wear. Known for impeccable tailoring and quality fabrics.', target_audience: 'Business professionals, men 30-55', price_range: '$$$', website: 'https://ghabbourfashion.com', city: 'Cairo', ships_to: 'Egypt', specialties: ['Bespoke Suits', 'Corporate Wear', 'Premium Ties & Accessories'], certifications: ['Made in Egypt'], ai_searches: 190 },
  { name: 'Mohito Egypt', slug: 'mohito-egypt', style: ['Feminine', 'Trendy', 'Contemporary'], description: 'Polish fashion brand with growing presence in Egypt. Offers feminine, elegant styles at accessible prices. Popular among Egyptian women for work and occasion wear.', target_audience: 'Women 22-40, feminine style', price_range: '$$', website: 'https://mohito.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Feminine Dresses', 'Elegant Work Wear', 'Evening Collections'], certifications: [], ai_searches: 450 },
  { name: 'Oasis Egypt', slug: 'oasis-egypt', style: ['Feminine', 'Contemporary', 'Trendy'], description: 'British fashion brand available in Egypt known for feminine, modern designs. Offers affordable occasion wear and everyday fashion for the modern Egyptian woman.', target_audience: 'Women 20-40', price_range: '$$', website: 'https://oasis-stores.com', city: 'Cairo', ships_to: 'Egypt (select stores)', specialties: ['Occasion Dresses', 'Feminine Tops', 'Summer Collections'], certifications: [], ai_searches: 380 },
  { name: 'River Island Egypt', slug: 'river-island-egypt', style: ['Trendy', 'Streetwear', 'Contemporary'], description: 'British high street brand available in Egypt. Known for on-trend fashion at mid-range prices, popular among young Egyptian fashion lovers.', target_audience: 'Youth & young adults 16-35', price_range: '$$', website: 'https://riverisland.com', city: 'Cairo', ships_to: 'Egypt (select stores)', specialties: ['Denim', 'Party Wear', 'Seasonal Trends'], certifications: [], ai_searches: 520 },
  { name: 'Tommy Hilfiger Egypt', slug: 'tommy-hilfiger-egypt', style: ['Preppy', 'Contemporary', 'Luxury'], description: 'American premium fashion brand with flagship stores in Egypt. Known for classic American style with preppy aesthetic. Highly sought after by the Egyptian upper-middle class.', target_audience: 'Men & women 18-45, preppy style, upper class', price_range: '$$$', website: 'https://tommy.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Classic Polo Shirts', 'Denim Collections', 'Accessories & Fragrances'], certifications: [], ai_searches: 1230 },
  { name: 'Calvin Klein Egypt', slug: 'calvin-klein-egypt', style: ['Minimalist', 'Luxury', 'Contemporary'], description: 'American luxury fashion brand with strong presence in Egypt. Known for minimalist aesthetic, premium denim and iconic underwear. Available in major Egyptian malls.', target_audience: 'Men & women 20-45, minimalist luxury', price_range: '$$$', website: 'https://calvinklein.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Premium Denim', 'CK Underwear', 'Minimalist RTW'], certifications: [], ai_searches: 1450 },
  { name: 'Lacoste Egypt', slug: 'lacoste-egypt', style: ['Preppy', 'Sporty', 'Luxury'], description: 'French lifestyle brand with flagship stores in Egypt. Known for the iconic polo shirt and premium sportswear with French elegance.', target_audience: 'Men & women 20-50, preppy sporty style', price_range: '$$$', website: 'https://lacoste.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Iconic Polo Shirts', 'Premium Sportswear', 'Tennis-inspired Collections'], certifications: [], ai_searches: 980 },
  { name: 'Polo Ralph Lauren Egypt', slug: 'polo-ralph-lauren-egypt', style: ['Preppy', 'Luxury', 'Classic'], description: 'American luxury fashion brand available in Egypt. Embodies classic American style and luxury lifestyle. Highly coveted among affluent Egyptian shoppers.', target_audience: 'Affluent men & women 25-55', price_range: '$$$', website: 'https://ralphlauren.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Classic Polo Shirts', 'Premium Knitwear', 'Lifestyle Collections'], certifications: [], ai_searches: 1100 },
  { name: 'Guess Egypt', slug: 'guess-egypt', style: ['Glamorous', 'Contemporary', 'Denim'], description: 'American fashion brand with multiple stores across Egypt. Known for glamorous denim, bold accessories and lifestyle fashion popular among Egyptian youth.', target_audience: 'Men & women 18-40, glamorous style', price_range: '$$', website: 'https://guess.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Premium Denim', 'Logo Bags', 'Seasonal RTW'], certifications: [], ai_searches: 1340 },
  { name: 'Michael Kors Egypt', slug: 'michael-kors-egypt', style: ['Luxury', 'Contemporary', 'Accessories'], description: 'American luxury fashion brand with growing presence in Egypt. Known for premium handbags, watches and ready-to-wear. Extremely popular among affluent Egyptian women.', target_audience: 'Women 25-50, luxury accessories, upper class', price_range: '$$$', website: 'https://michaelkors.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Luxury Handbags', 'Premium Watches', 'Jet Set Lifestyle'], certifications: [], ai_searches: 1560 },
  { name: 'Coach Egypt', slug: 'coach-egypt', style: ['Luxury', 'Accessories', 'Contemporary'], description: 'American luxury leather goods brand available in Egypt. Known for premium leather handbags, wallets and accessories with New York heritage.', target_audience: 'Women 25-50, luxury bags, accessories', price_range: '$$$', website: 'https://coach.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Premium Leather Bags', 'Tabby Collection', 'Leather Accessories'], certifications: [], ai_searches: 1280 },
  { name: 'Kenzo Egypt', slug: 'kenzo-egypt', style: ['Luxury', 'Avant-garde', 'Artistic'], description: 'French luxury fashion house available in select Egyptian retailers. Known for bold prints, floral motifs and artistic approach to fashion.', target_audience: 'Fashion-forward 25-45, luxury', price_range: '$$$$', website: 'https://kenzo.com', city: 'Cairo', ships_to: 'Egypt (select retailers)', specialties: ['Tiger Motif Collections', 'Bold Print RTW', 'Artistic Accessories'], certifications: [], ai_searches: 420 },
  { name: 'Levi\'s Egypt', slug: 'levis-egypt', style: ['Casual', 'Denim', 'Streetwear'], description: "America's most iconic denim brand with multiple stores across Egypt. The go-to destination for quality jeans for all Egyptians.", target_audience: 'All ages, denim lovers', price_range: '$$', website: 'https://levis.com', city: 'Cairo', ships_to: 'Egypt-wide', specialties: ['501 Classic Jeans', 'Trucker Jacket', 'Sustainable Denim'], certifications: ['Water<Less Technology'], ai_searches: 2400 },
  { name: 'Adidas Egypt', slug: 'adidas-egypt', style: ['Sporty', 'Streetwear', 'Athleisure'], description: 'German sportswear giant with massive presence across Egypt. From performance sports gear to streetwear collections, Adidas is one of the most worn brands in Egypt.', target_audience: 'All ages, sports & streetwear', price_range: '$$', website: 'https://adidas.com', city: 'Cairo', ships_to: 'Egypt-wide', specialties: ['Stan Smith Sneakers', 'Originals Collections', 'Performance Sports Gear'], certifications: ['Parley Ocean Plastic'], ai_searches: 3200 },
  { name: 'Nike Egypt', slug: 'nike-egypt', style: ['Sporty', 'Streetwear', 'Athleisure'], description: "World's leading sportswear brand with strong presence in Egypt. Dominates both the sports performance and streetwear segments in the Egyptian market.", target_audience: 'All ages, sports & fashion', price_range: '$$', website: 'https://nike.com', city: 'Cairo', ships_to: 'Egypt-wide', specialties: ['Air Force 1', 'Jordan Brand', 'Performance Running Gear'], certifications: ['Move to Zero Sustainability'], ai_searches: 4100 },
  { name: 'New Balance Egypt', slug: 'new-balance-egypt', style: ['Sporty', 'Athleisure', 'Streetwear'], description: 'American athletic brand growing fast in Egypt. Known for premium running shoes and retro-inspired sneakers beloved by Egyptian streetwear community.', target_audience: 'Youth & adults 16-40, sneaker culture', price_range: '$$', website: 'https://newbalance.com', city: 'Cairo', ships_to: 'Egypt (select stores)', specialties: ['990 Sneakers', 'Running Collections', '574 Retro'], certifications: [], ai_searches: 1100 },
  { name: 'Puma Egypt', slug: 'puma-egypt', style: ['Sporty', 'Streetwear', 'Athleisure'], description: 'German sportswear brand with strong retail presence in Egypt. Known for performance sports gear and street-inspired collections popular among Egyptian youth.', target_audience: 'Youth & adults 16-40, sporty style', price_range: '$$', website: 'https://puma.com', city: 'Cairo', ships_to: 'Egypt-wide', specialties: ['Classic Suede Sneakers', 'Ferrari Collection', 'Sports Performance'], certifications: [], ai_searches: 1380 },
  { name: 'Swarovski Egypt', slug: 'swarovski-egypt', style: ['Luxury', 'Accessories', 'Glamorous'], description: 'Austrian luxury crystal brand with flagship stores in Egyptian malls. Extremely popular among Egyptian women for jewellery, accessories and home decor.', target_audience: 'Women 20-55, accessories, gifting', price_range: '$$$', website: 'https://swarovski.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Crystal Jewellery', 'Limited Collections', 'Gift Collections'], certifications: [], ai_searches: 1890 },
  { name: 'Pandora Egypt', slug: 'pandora-egypt', style: ['Contemporary', 'Accessories', 'Feminine'], description: 'Danish jewellery brand popular across Egypt for customizable charm bracelets and affordable luxury jewellery. One of the top gifting destinations in Egyptian malls.', target_audience: 'Women 16-50, jewellery, gifting', price_range: '$$', website: 'https://pandora.net', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Charm Bracelets', 'Sterling Silver Collections', 'Lab-grown Diamonds'], certifications: ['Responsible Jewellery Council'], ai_searches: 2100 },
  { name: 'Boyner Egypt', slug: 'boyner-egypt', style: ['Contemporary', 'Family', 'Casual'], description: 'Turkish multi-brand fashion retailer available in Egypt. Offers curated selection of local and international fashion brands under one roof.', target_audience: 'Families, all ages', price_range: '$$', website: 'https://boyner.com', city: 'Cairo', ships_to: 'Egypt (select stores)', specialties: ['Multi-brand Selection', 'Family Fashion', 'Seasonal Collections'], certifications: [], ai_searches: 340 },
  { name: 'Virgin Mega Store Fashion Egypt', slug: 'virgin-megastore-fashion', style: ['Streetwear', 'Contemporary', 'Pop Culture'], description: 'Fashion and lifestyle brand available at Virgin Megastore Egypt locations. Offers pop culture-inspired fashion, accessories and merchandise.', target_audience: 'Youth 14-30, pop culture fans', price_range: '$', website: 'https://virgenmegastore.com', city: 'Cairo', ships_to: 'Egypt (in-store)', specialties: ['Licensed Merch', 'Pop Culture Tees', 'Accessories'], certifications: [], ai_searches: 280 },
  { name: 'Couverture Egypt', slug: 'couverture-egypt', style: ['Luxury', 'Contemporary', 'Feminine'], description: 'Egyptian luxury women\'s fashion brand offering sophisticated ready-to-wear for the modern Egyptian woman. Known for quality fabrics and elegant cuts.', target_audience: 'Affluent women 28-50', price_range: '$$$', website: 'https://couvertureegypt.com', city: 'Cairo', ships_to: 'Egypt & Gulf', specialties: ['Luxury RTW', 'Occasion Wear', 'Premium Accessories'], certifications: ['Made in Egypt'], ai_searches: 240 },
  { name: 'Loft Egypt', slug: 'loft-egypt', style: ['Casual', 'Contemporary', 'Feminine'], description: 'American casual fashion brand for women available in Egypt. Known for relaxed, feminine styles perfect for everyday wear at accessible prices.', target_audience: 'Women 22-45, casual everyday wear', price_range: '$$', website: 'https://loft.com', city: 'Cairo', ships_to: 'Egypt (select stores)', specialties: ['Casual Dresses', 'Workwear Basics', 'Relaxed Denim'], certifications: [], ai_searches: 310 },
  { name: 'Batik Boutique Egypt', slug: 'batik-boutique-egypt', style: ['Bohemian', 'Heritage', 'Artisan'], description: 'Egyptian boutique specializing in handcrafted batik fashion blending traditional African and Middle Eastern textile art with contemporary design.', target_audience: 'Women 25-50, artisan fashion, heritage lovers', price_range: '$$', website: 'https://batikboutiqueegypt.com', city: 'Cairo', ships_to: 'Egypt & Worldwide', specialties: ['Hand-dyed Batik Pieces', 'Artisan Kaftans', 'Heritage Textiles'], certifications: ['Handmade', 'Artisan Crafted'], ai_searches: 190 },
  { name: 'Egyptian Cotton Store', slug: 'egyptian-cotton-store', style: ['Minimalist', 'Sustainable', 'Luxury'], description: 'Premium Egyptian cotton fashion and home brand celebrating the world-famous extra-long staple cotton. Offers luxury basics and bedding made from authentic Egyptian cotton.', target_audience: 'Quality-conscious buyers, 28-60', price_range: '$$$', website: 'https://egyptiancottonstore.com', city: 'Cairo', ships_to: 'Worldwide', specialties: ['Extra-long Staple Cotton Basics', 'Luxury Loungewear', 'Premium Bedding'], certifications: ['Egyptian Cotton Certified', 'GOTS Certified'], ai_searches: 560 },
];

async function seed() {
  console.log(`Seeding ${brands.length} brands...`);
  const { data, error } = await supabase.from('brands').insert(
    brands.map(b => ({
      ...b,
      top_queries: [],
      certifications: b.certifications ?? [],
      plan: 'free',
      embed_installed: false,
    }))
  );
  if (error) {
    console.error('Error:', error.message);
  } else {
    console.log('Done! Brands seeded successfully.');
  }
}

seed();
